---

- name: reload systemd
  become: True
  systemd:
    daemon-reload: True

- name: restart mat2-web
  service:
    name: mat2-web
    state: restarted

- name: restart monit
  service:
    name: monit
    state: restarted
