---
scenario:
  name: default

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: mat2-web-buster64
    box: debian/buster64

provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
    enabled: false
