---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: mat2-web-buster64
    box: debian/buster64

dependency:
  name: galaxy
  options:
    force: false

lint: yamllint .

provisioner:
  name: ansible
  become: true
